### ISSUE TITLE
update version on PyPi?

### ISSUE THREAD

**Issue by martey** [sandersnewmedia/django-session-cleanup#3]
Would it be possible to update the django-session-cleanup package on PyPi with a version 0.0.2, containing the changes from #1?

**Comment by BabisK** [comment]
I second that!

**Comment by mwcbrent** [comment]
@elijahr I think this is on your PyPi account.  Can you update?

**Comment by martey** [comment]
I've been working on this, but wanted to add some additional improvements (automated testing, etc.). I'm not 100% sure when I will have time to finish it, but I should be able to get to it sometime in the next few weeks.

**Comment by martey** [comment]
This is fixed - see https://pypi.org/project/django-session-cleanup/1.0.0/.
